import { AnimatedLink, AnimatedButton } from './AnimatedButton';
import { t, useLanguage } from '../i18n';
import React, { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, BookOpen, Check, ChevronDown, Users, MessageSquare, ShoppingBag } from 'lucide-react';
export const incomeNotice = '$20.000 pro Monat sind ein ambitioniertes Ziel und kein garantiertes Einkommen. Ergebnisse hängen unter anderem von Reichweite, Zielgruppe, Angebot, Preisen, Conversion, Konsistenz, Marktbedingungen und persönlicher Umsetzung ab.';
export function ApplyButton({children='Jetzt für die Academy bewerben'}:{children?:React.ReactNode}) {
  useLanguage();
 return <AnimatedLink animateArrow href="#section-13" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#20C997] hover:bg-[#169B74] text-[#080808] px-6 py-3 text-sm font-bold transition-colors">{t(children)}</AnimatedLink>; }
export function SectionProgress(){
  useLanguage();
const [active,setActive]=useState(1);useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)setActive(Number(entry.target.id.split('-')[1]));}),{rootMargin:'-20% 0px -65% 0px'});document.querySelectorAll('main > section').forEach(el=>observer.observe(el));return()=>observer.disconnect();},[]);return <div className="hidden xl:block fixed right-4 bottom-6 z-40 rounded-full border border-white/15 bg-black/70 px-3 py-2 text-xs font-mono text-white/70" aria-label={t(`Sektion ${active} von 13`)}>{t(String(active).padStart(2,'0'))}{t(" / 13")}</div>;}
export const academyModules=[['Deine Marke','Finde deine Positionierung und entwickle deinen persönlichen Stil.','Notiere, für wen du Content machst und was deine Marke besonders macht.'],['Dein Content-System','Plane und erstelle Content, der zu dir und deiner Zielgruppe passt.','Lege deine Themen, Formate und einen realistischen Wochenplan fest.'],['Deine AI-Unterstützung','Nutze KI für Content, Gespräche und wiederkehrende Aufgaben.','Bestimme deine Sprache, deine Grenzen und deine Freigaben.'],['Deine Produkte','Verwandle deine Inhalte in attraktive digitale Angebote.','Beschreibe den Nutzen und den Umfang deines ersten digitalen Angebots.'],['Dein CRM-System','Organisiere Käufer, Angebote, Gespräche und Follow-ups.','Ordne Kontakte, dokumentiere Interessen und plane den nächsten Schritt.'],['Dein Wachstum','Verbessere Social Media, Verkäufe und Käuferbindung.','Prüfe regelmäßig, welche Inhalte und Angebote zu deiner Zielgruppe passen.']];
export function AcademySection(){
  useLanguage();
const [active,setActive]=useState(0);return <section id="section-9" className="landing-section bg-[#0A0A0C] px-4 sm:px-6 lg:px-8" aria-label={t("The Katharina Method")}><div className="max-w-7xl mx-auto text-center space-y-8"><div className="space-y-3"><p className="text-xs uppercase tracking-widest font-bold text-[#20C997]">{t("THE KATHARINA METHOD")}</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold font-display text-white">{t("Deine Marke. Dein Business.")}<br/><span className="text-[#20C997]">{t("Deine Zukunft.")}</span></h2><p className="text-sm sm:text-base text-white/80">{t("In der Katharina Academy lernst du das komplette System Schritt für Schritt.")}</p></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{t(academyModules.map(([title,text],i)=><AnimatedButton animationVariant="card" key={title} onClick={()=>setActive(i)} aria-pressed={i===active} aria-controls="academy-module-preview" className={`rounded-3xl border p-6 text-left transition-all hover:-translate-y-1 ${i===active?'border-[#20C997] bg-[#171518]':'border-white/10 bg-[#121113]'}`}><div className="flex items-center justify-between text-[#20C997] mb-4"><BookOpen className="w-6 h-6"/><span className="text-xs font-mono">{t("MODUL 0")}{t(i+1)}</span></div><h3 className="text-xl font-display font-bold text-white">{t(title)}</h3><p className="text-sm text-white/70 mt-3">{t(text)}</p></AnimatedButton>))}</div><div id="academy-module-preview" className="rounded-2xl border border-white/10 bg-[#141416] p-6 text-left max-w-3xl mx-auto" aria-live="polite"><p className="text-xs text-[#20C997] font-bold mb-2">{t("MODULVORSCHAU · 0")}{t(active+1)}{t(" / 06")}</p><h3 className="text-lg font-bold text-white">{t("Dein nächster Schritt: ")}{t(academyModules[active][0])}</h3><p className="text-sm text-white/75 mt-3">{t(academyModules[active][2])}</p><div className="flex flex-wrap gap-4 text-xs text-white/60 mt-4"><span>{t("Videolektionen")}</span><span>{t("Kurze Checklisten")}</span><span>{t("Katharinas persönliche Tipps")}</span><span>{t("SnapSell-Einrichtung")}</span></div><p className="text-xs text-white/50 mt-3">{t("Vorschau der Module. Vollständige Lerninhalte folgen im gewählten Programm.")}</p></div><ApplyButton>{t("Der Katharina Academy beitreten")}</ApplyButton></div></section>;}
export function CRMDetails(){
  useLanguage();
const [active,setActive]=useState(0);const tabs=['Käuferprofil','Gespräch','Sales-Pipeline','Angebot'];const features=['Käuferprofile','Kontakte und Notizen','Gesprächsverläufe','Tags und Zielgruppen','einfache Sales-Pipeline','Aufgaben und Follow-ups','Medienbibliothek','Produkte und Angebote','Verkäufe und Analysen','Teamzugänge'];return <div className="w-full max-w-4xl space-y-5 text-left"><div className="grid sm:grid-cols-2 gap-5"><div className="rounded-2xl bg-[#141416] border border-white/10 p-5"><h3 className="text-white font-bold mb-3">{t("Direkt verkaufen")}</h3><p className="text-sm text-white/70 leading-relaxed">{t("Content hochladen → Produkt erstellen → Preis festlegen → Payment-Link teilen → Zahlung erhalten → Inhalt ausliefern")}</p></div><div className="rounded-2xl bg-[#141416] border border-white/10 p-5"><h3 className="text-white font-bold mb-3">{t("Business verwalten")}</h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-2">{t(features.map(item=><span key={item} className="text-xs text-white/70 flex gap-2"><Check className="w-3 h-3 text-[#20C997] shrink-0"/>{t(item)}</span>))}</div></div></div><div className="rounded-2xl bg-[#141416] border border-white/10 p-5"><div className="flex flex-wrap gap-2 mb-5" aria-label={t("CRM-Vorschau")}>{t(tabs.map((name,i)=><AnimatedButton key={name} aria-pressed={active===i} onClick={()=>setActive(i)} className={`rounded-full px-3 py-2 text-xs border ${active===i?'border-[#20C997] text-[#20C997]':'border-white/10 text-white/70'}`}>{t(name)}</AnimatedButton>))}</div><div aria-live="polite" className="grid sm:grid-cols-3 gap-4 min-h-28">{t((active===0?['Demo-Kontakt A','Interesse: Content-Planung','Notiz: Rückfrage zum Workbook']:active===1?['Neue Nachricht: Ich suche Content-Ideen.','Antwort: Welches Format interessiert dich?','Nächster Schritt: persönlich nachfassen']:active===2?['Interesse erkannt','Angebot geteilt','Follow-up geplant']:['Digitales Workbook · Beispiel','Payment-Link → Zahlung','Inhalt ausliefern']).map((line,i)=><div key={line} className="p-4 rounded-xl bg-black/40 border border-white/10"><span className="text-xs text-[#20C997]">{t("0")}{t(i+1)}</span><p className="text-sm text-white/80 mt-2">{t(line)}</p></div>))}</div><p className="text-xs text-white/50 mt-4">{t("Illustrative CRM-Vorschau · keine echten Kundendaten oder Zahlungen.")}</p></div></div>;}
export function MexicoExperience(){
  useLanguage();
return <div id="mexico-experience" className="w-full rounded-3xl border border-white/10 bg-[#141416] p-6 sm:p-8 grid lg:grid-cols-2 gap-8 text-left"><div className="space-y-4"><p className="text-xs text-[#20C997] uppercase tracking-widest font-bold">{t("KATHARINA CREATOR EXPERIENCE")}</p><h3 className="text-2xl sm:text-3xl font-display font-bold text-white">{t("Masterclass mit Katharina in Mexiko.")}</h3><p className="text-sm text-white/75">{t("Ausgewählte Creatorinnen können an einer intensiven Masterclass in einer hochwertigen Villa in Mexiko teilnehmen.")}</p><p className="text-xs text-[#D7BE8A]">{t("Katharina Creator Villa – Mexico")}</p><ApplyButton>{t("Für die Experience bewerben")}</ApplyButton></div><div className="grid sm:grid-cols-2 gap-3">{t(['persönliches Coaching mit Katharina','Social-Media-Workshops','AI Content Training','SnapSell CRM Einrichtung','Produkt- und Preisstrategie','professionelle Fotoshootings','filmreife Videoproduktionen','Networking mit Creatorinnen'].map(item=><div className="flex gap-2 items-start text-xs text-white/80 rounded-xl bg-black/30 p-3" key={item}><Check className="w-4 h-4 text-[#20C997] shrink-0"/>{t(item)}</div>))}</div></div>;}
const questions=[['Muss ich bereits eine große Reichweite haben?','Nein. Die Academy ist für neue, aktive und etablierte Creatorinnen geeignet.'],['Muss ich technisch erfahren sein?','Nein. Das System wird einfach und Schritt für Schritt erklärt.'],['Ersetzt KI meine Persönlichkeit?','Nein. KI unterstützt deine Arbeit. Du bestimmst deine Identität, deinen Stil, deine Grenzen und deine Freigaben.'],['Ist eine internationale Reise garantiert?','Nein. Events, Produktionen und Reisen sind zusätzliche Möglichkeiten für ausgewählte Mitglieder.'],['Sind bestimmte Umsätze garantiert?','Nein. Die Academy stellt Systeme, Wissen und Unterstützung bereit. Ergebnisse hängen von deiner Ausgangssituation, deinem Angebot und deiner Umsetzung ab.']];
export function FAQAccordion(){
  useLanguage();
const [active,setActive]=useState<number|null>(null);return <div className="relative z-10 max-w-4xl mx-auto mt-14 text-left"><h3 className="text-2xl font-display font-bold text-white mb-6">{t("Häufige Fragen")}</h3>{t(questions.map(([q,a],i)=><div key={q} className="border-b border-white/10"><h4><AnimatedButton id={`faq-q-${i}`} aria-expanded={active===i} aria-controls={`faq-a-${i}`} onClick={()=>setActive(active===i?null:i)} className="flex justify-between items-center gap-4 w-full py-5 text-left text-sm text-white/90">{t(q)}<ChevronDown className={`w-4 h-4 shrink-0 transition-transform ${active===i?'rotate-180':''}`}/></AnimatedButton></h4><p id={`faq-a-${i}`} role="region" aria-labelledby={`faq-q-${i}`} hidden={active!==i} className="text-sm text-white/70 pb-5 leading-relaxed">{t(a)}</p></div>))}</div>;}
export function useFocusTrap(open:boolean,close:()=>void){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!open)return;const prior=document.activeElement as HTMLElement;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';const nodes=():HTMLElement[]=>Array.from(ref.current?.querySelectorAll('button,a[href],input,select,[tabindex="0"]')||[]) as HTMLElement[];nodes()[0]?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')close();if(e.key==='Tab'){const list=nodes();if(e.shiftKey&&document.activeElement===list[0]){e.preventDefault();list.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===list.at(-1)){e.preventDefault();list[0]?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=overflow;prior?.focus();};},[open]);return ref;}

